# Generated by Django 5.1 on 2024-08-22 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_category_table_alter_chatmessage_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='events',
            field=models.ManyToManyField(blank=True, through='api.EventRegistration', to='api.events'),
        ),
        migrations.AlterField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, through='api.GroupMembership', to='api.group'),
        ),
    ]
